"""update chat  migrate

Revision ID: 9e5c5f882b5b
Revises: 67b4c079aa37
Create Date: 2024-08-05 11:44:25.673674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e5c5f882b5b'
down_revision = '67b4c079aa37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inserted_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inserted_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('inserted_date')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('inserted_date')

    # ### end Alembic commands ###
